# https://www.mkdocs.org/getting-started/
site_name: Pi Food Computer

nav:
  - Home: index.md
  - About: about.md
theme:
  name: mkdocs
  shortcuts:
    search: 83   # s

repo_url: https://github.com/benlascelle/pi-food-computer
edit_uri: edit/main/docs/
markdown_extensions:
  - toc:
      permalink: true
plugins:
  - search:
      indexing: 'full'