# https://www.mkdocs.org/getting-started/
site_name: Pi Food Computer

nav:
  - Home: index.md
  - About: about.md
theme: readthedocs
repo_url: https://github.com/benlascelle/pi-food-computer
edit_uri: edit/master/docs/
markdown_extensions:
  - toc:
      permalink: true
plugins:
  - search:
      indexing: 'full'