name: github pages2

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build_test:
        runs-on: ubuntu-20.04
        concurrency:
          group: ${{ github.workflow }}-${{ github.ref }}
        steps:
          - uses: actions/checkout@v2
    
          - name: Setup mdBook
            uses: peaceiris/actions-mdbook@v2
            with:
              mdbook-version: '0.4.10'
    
          - run: mdbook build
    
          - name: Deploy
            uses: peaceiris/actions-gh-pages@v3
            if: ${{ github.ref == 'refs/heads/main' }}
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./book
    # Build job
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Pages
          id: pages
          uses: actions/configure-pages@v3
        - name: Build with Jekyll
          uses: actions/jekyll-build-pages@v1
          with:
            source: ./book/
            destination: ./_site
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v2
  
    # Deployment job
    deploy:
      environment:
        name: github-pages
        url: ${{steps.deployment.outputs.page_url}}
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2